### ISSUE TITLE
This project needs a maintainer

### ISSUE THREAD

**Issue by bashu** [praekelt/django-likes#38]
Hi,

This repository seems to lack maintenance, I propose myself as a new maintainer.

Could you give me the right to push in your repository or just transfer it on my account in github?

Thank you!

**Comment by bashu** [comment]
We still use it some legacy projects and I am willing to keep it maintained. If you are not sure about me, for example I maintain (or helping to maintain):

https://github.com/shanx/django-maintenancemode

https://github.com/adamcharnock/django-tz-detect

Also I adopted few Django projects and still continue maintaining them, biggest example:

https://github.com/bashu/django-easy-maps

PS: I also maintain https://github.com/bashu/django-secretballot

**Comment by bittner** [comment]
We'd  also be interested in having this package more actively maintained.

My vision of a "likes" app is to (optionally) provide additional benefit to liking "locally". We have a use case where we count a collective sum of "local likes" and "likes" across a selection of social networks.

- We want our visitors to also go to, say, Instagram, Facebook, etc. and "like" our content there _in addition_.
- We then scrape or query those likes via API backend-side (not client-side, because I don't want our visitors to be tracked by the social networks) and fill in the values in the model. Of course you could cheat and set the values in the model manually. :smirk: 
- The front-end shows the heart :heart: for "local liking" and could allow to visit the social networks for liking with a simple click.

**Comment by bashu** [comment]
cc @jerith, @miltontony and @bduvenhage

**Comment by bashu** [comment]
anyone??

**Comment by bashu** [comment]
I have released `django-secretballot==2.0.0` few days ago, and can take on this project

**Comment by markupguy** [comment]
Added @bashu as maintainer
